In [1]:
import numpy as np 
import pandas as pd

numpy gives better storage, readymade functions, relatively memory usage 
jitni jagah chahiye utni jagah ka use krlo

In [4]:
myarr = np.array([3,5,6,7])

we have successfully made our numpy array 

In [5]:
myarr

array([3, 5, 6, 7])

In [8]:
myarr.dtype

dtype('int32')

In [9]:
myarr[1]

5

making a 2d array 

In [20]:
hahaarr = np.array([
    [1,2,3],
    [2,4,5],
    [2,6,7]
])

In [21]:
hahaarr

array([[1, 2, 3],
       [2, 4, 5],
       [2, 6, 7]])

In [22]:
hahaarr[0][2]

3

In [23]:
hahaarr[0,1]

2

In [24]:
hahaarr[0][0] = 45
#to change value stored at a particular index 

In [25]:
hahaarr

array([[45,  2,  3],
       [ 2,  4,  5],
       [ 2,  6,  7]])

array creation methods in numpy. there are five methods to do so 
1. conversion from other python structures 
2. intrinsic numpy array creation object 
and other ajeeb ajeeb ones. These much will do for us right now


how we made an array just now is an example of the first method to go about it 

In [27]:
hahaarr.dtype

dtype('int32')

In [28]:
hahaarr.size

9

In [29]:
hahaarr.shape

(3, 3)

In [33]:
zeros = np.zeros((2,5))

In [34]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

that creates an array of size 2,5 filled with zeroes 

we can also create a numpy array of range 15 where all entries are just 1 to 15 natural numbers 

In [37]:
newarrr = np.arange(15)

In [38]:
newarrr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [39]:
arr2 = np.arange(10,2)

In [40]:
arr2

array([], dtype=int32)

In [41]:
arr3 = np.linspace(1,50,10)

In [42]:
arr3

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

this gives us an array of 10 elements where 1 to 50 are equally spaced 

In [51]:
arr4 = np.identity(3)

In [52]:
arr4

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

gives us an identity matrix of 3x3

In [53]:
arr5 = np.arange(99)

In [54]:
arr5

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

we can also reshape our original dataframe

In [55]:
arr5.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

to bring it back into 1,99 form

In [56]:
arr5.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [57]:
arr5.shape

(99,)

In [58]:
arr6 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [59]:
arr6

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [61]:
arr6.sum(axis=0)


array([ 6, 15, 24])

In [62]:
arr6.sum(axis=1)

array([ 6, 15, 24])

In [64]:
arr6.T 
#transpose

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [65]:
arr6.flat

In [67]:
for item in arr6.flat:
    print(item)

    #prints all items in the array 

1
2
3
4
5
6
7
8
9


In [69]:
arr6.ndim #to know the dimensions of your array

2

In [71]:
arr6.nbytes #total bytes/storage consumed by all array elements

36

In [72]:
arr7 = np.array([1,2,3,4])

In [74]:
arr7.argmax()  #gives index of the place where maximum value is stored 

3

In [75]:
arr7.argmin()

0

In [77]:
arr7.argsort() #gives us indices in an order where the value stoed in those index wouldve become sorted if replaced by the writen index 

array([0, 1, 2, 3], dtype=int64)

lets see how these methods work for a 2d array 

In [78]:
arr6.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [80]:
arr6.argmin() #first makes the 2d array into 1d by bringing all the elements in one line and then tells us the index of the min value in our 2d array 

0

In [81]:
arr6.argmax()

8

In [82]:
arr5

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [83]:
arr6

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [84]:
arr7

array([1, 2, 3, 4])

In [85]:
arr8 = np.array([
    [32,45,6],
    [22,66,77],
    [23,67,89]
])

In [86]:
arr6+arr8

array([[33, 47,  9],
       [26, 71, 83],
       [30, 75, 98]])

In [87]:
arr6*arr8

array([[ 32,  90,  18],
       [ 88, 330, 462],
       [161, 536, 801]])

In [89]:
np.sqrt(arr6) #takes element wise square root of all elements of te array 

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [91]:
arr6.sum()
#sums up all elements of the array 

45

In [92]:
arr6.max()

9

In [93]:
arr6.min()

1

how do you find an element from your numpy array ?

In [95]:
np.where(arr6>5)
#gives us the indices of all the places where element of arr6> 5

(array([1, 2, 2, 2], dtype=int64), array([2, 0, 1, 2], dtype=int64))

tuples (1,2), (2,0), (2,1),(2,2) are all the places where weve got elements>5

In [96]:
type(np.where(arr6>5))

tuple

In [98]:
np.count_nonzero(arr6)
#gives us number of non zero elements in our np array 

9